version: '3.7'

services:
  otus-social-network-core-postgres:
    image: "postgres:15.4"
    container_name: "otus-social-network-core-db"
    environment:
      POSTGRES_DB: "otus-social-network-core-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  otus-social-network-dialogue-postgres:
    image: "postgres:15.4"
    container_name: "otus-social-network-dialogue-db"
    environment:
      POSTGRES_DB: "otus-social-network-dialogue-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    expose:
      - 5433
    ports:
      - "5433:5433"
    command: -p 5433


  otus-sn-consul-discovery:
    image: consul:1.8.4
    container_name: consul-discovery
    command: consul agent -dev -client 0.0.0.0
    restart: always
    ports:
      - "8500:8500"