version: '3.7'

services:
  otus-social-network-postgres:
    image: "postgres:10.5"
    container_name: "otus-social-network-db"
    environment:
      POSTGRES_DB: "otus-social-network-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

#  kafka:
#    image: wurstmeister/kafka
#    container_name: kafka
#    links:
#      - zookeeper
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_PORT: "9092"
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
