server:
  port: 8081

spring:
  profiles:
    active: local
  #Application
  application:
    name: otus-social-network

  #Liquibase
  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:db-changelog/changelog-dev.xml}

  #JPA
  datasource:
    url: jdbc:postgresql://localhost:5432/otus-social-network-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        ddl-auto: none


management:
  endpoints:
    web:
      exposure:
        include: httptrace

